# Generated by Django 3.0.7 on 2020-06-19 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20200619_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='steps',
        ),
        migrations.AddField(
            model_name='step',
            name='steps_workFlow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='myapi.WorkFlow'),
        ),
    ]
