# Generated by Django 3.0.7 on 2020-06-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20200619_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='steps_workFlow',
            new_name='workFlow_steps',
        ),
    ]
