# Generated by Django 3.0.7 on 2020-06-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_auto_20200619_1806'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Step',
        ),
        migrations.RenameModel(
            old_name='Musician',
            new_name='WorkFlow',
        ),
    ]
